fart -i -r *.html images/ tsp-psp/images/
fart -i -r *.html tsp-psp/tsp-psp/images/ tsp-psp/images/
fart -i -r *.html assets/ tsp-psp/assets/
fart -i -r *.html tsp-psp/tsp-psp/assets/ tsp-psp/assets/
fart -i -r *.html arzolaescuela.github.io/favicon.ico arzolaescuela.github.io/tsp-psp/favicon.ico
fart -i -r *.html roles/ tsp-psp/roles/
fart -i -r *.html tsp-psp/tsp-psp/roles/ tsp-psp/roles/
fart -i -r *.html phases/ tsp-psp/phases/
fart -i -r *.html tsp-psp/tsp-psp/phases/ tsp-psp/phases/
fart -i -r *.html documents/ tsp-psp/documents/
fart -i -r *.html tsp-psp/tsp-psp/documents/ tsp-psp/documents/